services:
  - type: web
    name: hiiinishant-website
    env: node
    plan: free # Free plan is now possible since no persistent disk is needed on the frontend
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: BACKEND_URL
        sync: false # Enter your Render backend URL here (e.g. https://hiiinishant-backend.onrender.com)
